### ISSUE TITLE
Number of folders created can be very large.

### ISSUE THREAD

**Issue by biggstd** [SystemsGenetics/sra2gev#3]
We should consider changing the output directory structure into a nested one. See [similar functions in pynome](https://github.com/SystemsGenetics/pynome/blob/master/pynome/sra.py)

**Comment by spficklin** [comment]
Agreed, with 18K samples the directory structure gets a bit unwieldy....

**Comment by spficklin** [comment]
I belive this is fixed and we can close this issue @JohnHadish

**Comment by JohnHadish** [comment]
This issue has been fixed. You can now have sra2gev nest its output directories by changing the "outputdir_sra" and "outputdur_srx" in the "nextflow.config" file. They should be changed to a glob pattern that looks similar to this:
```
  outputdir_sra = { "${PWD}/${sra[0..2]}/${sra[3..4]}/${sra[5..6]}/${sra.drop(7)}/${sra}" }
  outputdir_srx = { "${PWD}/${srx[0..2]}/${srx[3..4]}/${srx[5..6]}/${srx.drop(7)}/${srx}" }
```
The above example will nest SRA numbers. The file "sra123456" would be put in the directory: ./sra/12/34/56/sra123456/
