### ISSUE TITLE
Probably do not need publishDir for sra and for srx (to be changed to run and sample)

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/sra2gev#9]
We probably can leave out the publishDir for sra (run). This would mean that we would have a final folder for each srx (sample) but none for the sra. Run fasta's would not be published, which I think would be fine, since the user will either have them locally, or they are available on ncbi.

**Comment by JohnHadish** [comment]
Related issue:
https://github.com/SystemsGenetics/sra2gev/issues/10

**Comment by spficklin** [comment]
I agree.  We don't need to keep the [SDE]RR directories around, only the SRX.

**Comment by JohnHadish** [comment]
Removed sra publishDir
